services:
  backend:
    container_name: backend-test
    build:
      context: ./backend
    env_file:
      - path: ./backend/.env.production
    ports:
      - 4200:4200
    depends_on:
      - database
    networks:
      - test-network
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-network
  frontend:
    # image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - frontend-node-modules:/app/node_modules
    restart: always
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - test-network
  nginx:
    build:
      context: ./.nginx/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - frontend
      - backend
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
volumes:
  postgres_data:
  frontend-node-modules:
