services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    env_file:
      - ./backend/.env.production
    depends_on:
      - database

  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    # image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'

    volumes:
      - frontend-node-modules:/app/node_modules
      - frontend-build:/app/.next
    restart: always
    depends_on:
      - backend
  nginx:
    build:
      context: ./.nginx/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - frontend

volumes:
  postgres_data:
  frontend-build:
  frontend-node-modules:
